#!/bin/bash
# post-write-lint.sh — Lints after every source write.
# Stack: custom (static-html) | Generated by init-harness. Safe to customise.
set -euo pipefail

INPUT=$(cat)
TOOL=$(echo "$INPUT" | jq -r '.tool_name // ""')
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')

[ "$TOOL" != "Edit" ] && [ "$TOOL" != "Write" ] && exit 0
echo "$FILE" | grep -qE '\.(js|html|css)$' || exit 0

LINT_OUT=$(true 2>&1) || true

if echo "$LINT_OUT" | grep -qE '[Ee]rror'; then
  ERRORS=$(echo "$LINT_OUT" | head -30)
  MSG=$(jq -n --arg e "$ERRORS" \
    '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":("Lint errors — fix before proceeding:\n" + $e)}}')
  echo "$MSG"
fi
exit 0
