#!/bin/bash
# require-plan.sh — Blocks source edits unless a plan file exists.
# Generated by init-harness. Safe to customise.
set -euo pipefail

INPUT=$(cat)
TOOL=$(echo "$INPUT" | jq -r '.tool_name // ""')
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')

# Pass-through: non-write tools, and writes to .claude/ or CLAUDE.md itself
[ "$TOOL" != "Edit" ] && [ "$TOOL" != "Write" ] && exit 0
echo "$FILE" | grep -qE '(\.claude/|CLAUDE\.md)' && exit 0

PLANS=$(find .claude/plans/ -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
if [ "$PLANS" -eq 0 ]; then
  MSG="No plan found in .claude/plans/. Run /engineering-planning to create one for this task, or add a quick .claude/plans/task.md with checkboxes for small fixes."
  PAYLOAD=$(jq -n --arg m "$MSG" \
    '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":$m}}')
  echo "$PAYLOAD"
  exit 0
fi
exit 0
