#!/bin/bash
# verify-before-stop.sh — Blocks completion if tests fail or plan items are open.
# Stack: custom (static-html) | Generated by init-harness. Safe to customise.
set -euo pipefail
FAIL=0

# 1. Tests
echo "▶ Running: true"
TEST_OUT=$(true 2>&1) || true
if echo "$TEST_OUT" | grep -qEi "(FAIL|failing|failed|error)"; then
  echo "❌ Tests failing — fix before stopping." >&2
  echo "$TEST_OUT" | tail -20 >&2
  FAIL=1
else
  echo "✅ Tests passed."
fi

# 2. Open plan items
PLAN=$(find .claude/plans/ -name "*.md" 2>/dev/null | sort | head -1)
if [ -n "$PLAN" ]; then
  OPEN=$(grep -cE "^[[:space:]]*- \[ \]" "$PLAN" 2>/dev/null || echo "0")
  if [ "$OPEN" -gt 0 ]; then
    echo "❌ $OPEN unchecked plan item(s) in $PLAN." >&2
    FAIL=1
  else
    echo "✅ All plan items complete."
  fi
else
  echo "⚠️  No plan file found — skipping plan check."
fi

# 3. Debug markers (warning only, does not block)
DIRTY=$(
  { git diff --name-only HEAD 2>/dev/null; git ls-files --others --exclude-standard; } \
  | sort -u \
  | xargs grep -lE "(FIXME|TODO\(claude\)|debugger;)" 2>/dev/null \
  || true
)
[ -n "$DIRTY" ] && echo "⚠️  Debug markers in: $DIRTY" >&2

[ "$FAIL" -eq 0 ] && exit 0 || exit 2
